[package]
name = "kaichi-test"
version = "0.1.0"
edition = "2021"
panic="unwind"

[dependencies]
bytemuck = { version = "1.15.0", features = ["derive"] }
nom = "7.1.3"

[lib]
crate-type = ["cdylib", "lib"]
